name: Check SonarQube Server Accessibility

on: push

jobs:
  checkSonarQube:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check SonarQube Server Accessibility
        shell: cmd
        run: |
          curl http://localhost:30000
