name: Terraform Code Analysis with SonarQube

on: [workflow_dispatch, schedule]
  

jobs:
  sonarQubeAnalysis:
    runs-on: self-hosted

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'adopt'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Java Version
        shell: powershell
        run: java -version

      - name: SonarQube Scan
        shell: powershell
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          C:\Users\FVS3KOR\Downloads\sonar-scanner-cli-4.7.0.2747-windows\sonar-scanner-4.7.0.2747-windows\bin\sonar-scanner.bat -X -D"sonar.projectKey=sonar.cpd.cross_project" -D"sonar.sources=." -D"sonar.host.url=$env:SONAR_HOST_URL" -D"sonar.login=$env:SONAR_TOKEN"

      - name: Terraform Format Check
        shell: powershell
        run: terraform fmt -check

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Validate
        shell: powershell
        run: terraform validate
