name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRIVY_VERSION: 0.53.0

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}
          trivy --version

      - name: Run Trivy scan
        run: |
          trivy config . --format sarif --output trivy_report.sarif

      - name: Install SonarScanner
        run: |
         
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH=$HOME/sonar-scanner-6.1.0.4477-linux-x64/bin:$PATH

      - name: Run SonarQube scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=sonar-terraform2 \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.externalIssuesReportPaths=tflint_report.json,trivy_report.sarif

      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - name: Quality Gate check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
